### ISSUE TITLE
leveldb deprecated fix

### ISSUE THREAD

**Issue by iFoggz** [Git-Jiro/homebrew-jiro#36]
i need u to look at these changes here and modify ur leveldb accordingly to fix a leveldb deprecated problem acey is having trying to compile the test version of the wallet.

https://github.com/Foggyx420/Gridcoin-Research/commit/9e79bd2f90530731866f05a936a7b04177984227

let me know if it works correctly please so i can pr this and get it into the main repo

**Comment by Git-Jiro** [comment]
OK. I will give it a try.

**Comment by iFoggz** [comment]
thank u

**Comment by Git-Jiro** [comment]
Yes, this worked. I had to fix some other unrelated compilation errors on the development branch as well, but then I got a Gridcoin binary.

These other compilation errors could be easily fixed by adding casts to (int). Those errors looked like this:

==== 8< ----
src/rpcrawtransaction.cpp:106:25: error: conversion from 'size_type' (aka 'unsigned long') to 'const json_spirit::Value_impl<json_spirit::Config_map<std::__1::basic_string<char> > >' is ambiguous
    res["bhLenght"]=msg.length();
                    ~~~~^~~~~~~~
src/json/json_spirit_value.h:46:9: note: candidate constructor
        Value_impl( bool               value );
        ^
src/json/json_spirit_value.h:47:9: note: candidate constructor
        Value_impl( int                value );
        ^
src/json/json_spirit_value.h:48:9: note: candidate constructor
        Value_impl( unsigned int       value );
        ^
src/json/json_spirit_value.h:49:9: note: candidate constructor
        Value_impl( int64_t     value );
        ^
src/json/json_spirit_value.h:50:9: note: candidate constructor
        Value_impl( uint64_t    value );
        ^
src/json/json_spirit_value.h:51:9: note: candidate constructor
        Value_impl( double             value );
        ^
==== 8< ----

**Comment by iFoggz** [comment]
yes ravon mentioned he forgot to fix this for OSX. i'll keep u updated. thats unrelated to leveldb thats json spirit

**Comment by ghost** [comment]
Thank you.

Regards,
William




On Sep 29, 2017, at 5:08 AM, Paul Jensen <notifications@github.com> wrote:

yes ravon mentioned he forgot to fix this for OSX. i'll keep u updated. thats unrelated to leveldb thats json spirit

**Comment by Git-Jiro** [comment]
I added a small patch to the Formula to cope with the json spirit issue. I hope my patch does not break anything. Could anybody check my commit here? https://github.com/Git-Jiro/homebrew-jiro/commit/2f568f142427e20a87d68ad02974848bec0ed277
