### ISSUE TITLE
App bundle for development branch

### ISSUE THREAD

**Issue by Git-Jiro** [Git-Jiro/homebrew-jiro#60]
The development branch of Gridcoin does not work with qmake and does not produce an app bundle anymore.

In my opinion a self contained app bundle is the better way to ship apps to users.
Therefore I would like to create an app bundle with the non qmake builds as well.

This tool might be helpful: https://github.com/auriamg/macdylibbundler/

**Comment by ghost** [comment]
Very interesting indeed. 
		

		Regards,
William
	_____________________________

**Comment by ghost** [comment]
Forgot to say that auto tools “make deploy” produces an app bundle.  
		
		

		Regards,
William
	




On Sun, Apr 8, 2018 at 5:43 PM +0900, "Martin Schimandl" <notifications@github.com> wrote:












The development branch of Gridcoin does not work with qmake and does not produce an app bundle anymore.


In my opinion a self contained app bundle is the better way to ship apps to users.

Therefore I would like to create an app bundle with the non qmake builds as well.


This tool might be helpful: https://github.com/auriamg/macdylibbundler/

**Comment by ghost** [comment]
I will compare the two.  The grc dmg is messed up, but the make deploy also places an app bundle outside of the dmg as well that worked fine last time I tried it. 
		
		

		Regards,
William
	




On Sun, Apr 8, 2018 at 6:01 PM +0900, "William Keene" <wkeene101@gmail.com> wrote:













	
		
		
	
		Forgot to say that auto tools “make deploy” produces an app bundle.  
		
		

		Regards,
William
	




On Sun, Apr 8, 2018 at 5:43 PM +0900, "Martin Schimandl" <notifications@github.com> wrote:












The development branch of Gridcoin does not work with qmake and does not produce an app bundle anymore.


In my opinion a self contained app bundle is the better way to ship apps to users.

Therefore I would like to create an app bundle with the non qmake builds as well.


This tool might be helpful: https://github.com/auriamg/macdylibbundler/

**Comment by Git-Jiro** [comment]
Thanks for the "make deploy" hint, Acey!
I settled for "make appbundle" and now this issue can be closed again! ;-)

**Comment by ghost** [comment]
cool thanks!

**Comment by ghost** [comment]
HI Jiro,

 

I tried your update for staging branch this morning upon reaching home. It works great!  I tried the development branch for fun and got different error messages confirming my belief that auto tools (AT) is causing the endless loop with “make” in the patch. 

 

I am curious to know if there is a way to command the existing auto tools in GRC development branch to compile using Jiro patch commands. IE. “./autogen.sh && ./configure && make deploy”. or "make app bundle".

 

Personally, I would like to see the Jiro patch have the ability to compile the production branch using AT as well, because you patch really is the best way to compile. Your patch compiles in half the time as GRC. Furthermore, The AT app when running, uses approximately half the memory as compared to the non AT compiled app.

 

Regards,

William
