### ISSUE TITLE
Gridcoin does not run on macOS 10.13

### ISSUE THREAD

**Issue by Pythonix** [Git-Jiro/homebrew-jiro#81]
According to a user on discord, Gridcoin does not run on macOS 10.13 (see image). Bitcoin, however, runs on even older versions of macOS . 
![image](https://user-images.githubusercontent.com/9782029/95962980-62cb9080-0e07-11eb-82fd-87e85a3818cb.png)

Are there any adjustments we can make to make Gridcoin run on older versions?

Thanks!

**Comment by Git-Jiro** [comment]
I build the binary using macOS images in Travis CI and Homebrew.
Which means Girdcoin supports whatever macOS versions are supported by a recent version of Homebrew.

**Comment by scribblemaniac** [comment]
I have macOS 10.13, and this formula runs perfectly fine on it. Perhaps they were using the binary/jiro-casks? The formula builds from source so it wouldn't make any sense for it to be incompatible with the user's macOS version.

**Comment by Git-Jiro** [comment]
Ah yes! That makes sense

**Comment by Pythonix** [comment]
Thanks @Git-Jiro @scribblemaniac .
However, the problem is with the precompiled application (dmg file). Is it possible to compile it to run on older operating systems?

**Comment by Git-Jiro** [comment]
I can try to downgrade the Travis CI machine and see if it produces a better result

**Comment by Pythonix** [comment]
@Git-Jiro I think it would be worthwhile to try this. It would be good if the dmg image runs on as many versions of macOS as possible.

**Comment by Git-Jiro** [comment]
Hi!
Once the travis build is done you should fine a DMG file here: https://github.com/Git-Jiro/homebrew-jiro/releases/tag/v5.0.2.0_macOS_10.13
Please test if this works with macOS 10.13

**Comment by RoboticMind** [comment]
On Discord they were saying that it still requires 10.14

**Comment by Git-Jiro** [comment]
Next attempt https://github.com/Git-Jiro/homebrew-jiro/releases/tag/v5.0.2.0_macOS_10.13_second_attempt

**Comment by Pythonix** [comment]
@Git-Jiro Thank you. The wallet now runs on macOS 10.13. But not on 10.11. Is it possible to use an even older XCode version?

**Comment by scribblemaniac** [comment]
To support older versions is more than just a matter of downgrading Xcode. You will also need to use an older version of the Qt framework as the latest 5.15 version only supports macOS 10.13+. However this is not trivial to do in homebrew because they don't do formula versioning anymore, and it's also worth nothing that they only support macOS versions 10.13 and higher now. If you were to downgrade the Qt version, you would loose official support for macOS 10.15, not to mention any bug fixes done in recent versions.

If you haven't figured it out already, I am of the opinion that it's not worth it to create binaries to support any earlier version of macOS. People can still compile it from source if they really need it. Keep in mind that support for 10.11 was dropped in Qt version 5.12, which was in use since about the end of 2018, and I am not aware of any large public outcry demanding the return of support since.

**Comment by Git-Jiro** [comment]
Thanks @scribblemaniac for doing the deep research into the Gridcoin dependencies.
Then I will keep the build at the lower XCode version for now, because this was a low effort change.

**Comment by Pythonix** [comment]
@scribblemaniac Thanks for this information. Under these circumstances it is understandable that we only support up to macOS 10.13. 

@Git-Jiro But could you do the XCode downgrade for the Master branch? So that future versions automatically run with macOS 10.13? Thanks!

**Comment by Git-Jiro** [comment]
Yes, will do.
